In [14]:
import pandas as pd

df = pd.DataFrame({
    "id":[1,2,3,4],
    "color":["red","blue","green","red"],
    "size":["Small","Medium","Large","Medium"],
    "price":[10,12,15,11]
})
df

   id  color    size  price
0   1    red   Small     10
1   2   blue  Medium     12
2   3  green   Large     15
3   4    red  Medium     11

In [15]:
# Step 2: declare the ordinal order
order = {"Small":1,"Medium":2,"Large":3}

In [16]:
# Step 3: convert the whole feature
# df["size_encoded"]=df["size"].map(order).astype(int)
df["size"]=df["size"].map(order).astype(int)

In [17]:
df

   id  color  size  price
0   1    red     1     10
1   2   blue     2     12
2   3  green     3     15
3   4    red     2     11