In [15]:
import pandas as pd
import numpy as np  

my_list = [['ALice', 25], ['Bob', 30], ['Charlie', 35]]

list_df = pd.DataFrame(my_list, columns=['Name', 'Age'] , index=['i', 'i', 'iii'])

list_df
#print(type(list_df))

        Name  Age
i      ALice   25
i        Bob   30
iii  Charlie   35

In [16]:
my_tuple = (('David', 40), ('Eva', 45), ('Frank', 50))
tuple_df = pd.DataFrame(my_tuple, columns=['Name', 'Age'] , index=['d', 'e', 'f'])
tuple_df
#print(type(tuple_df))

    Name  Age
d  David   40
e    Eva   45
f  Frank   50

In [17]:
my_dict = {'Name': ['George', 'Hannah', 'Ian'], 'Age': [55, 60, 65]}
dict_df = pd.DataFrame(my_dict, index=['a', 'b', 'c'])
dict_df 
#print(type(dict_df))

     Name  Age
a  George   55
b  Hannah   60
c     Ian   65

In [18]:
my_data = [
    {'Name' : 'Alice' , 'Age' : 25 , 'City' : 'New York'},
    {'Name' : 'Bob' , 'Age' : 30 , 'City' : 'Los Angeles'},
    {'Name' : 'Charlie' , 'Age' : 35 }
]

data_df = pd.DataFrame(my_data)

data_df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35          NaN