In [1]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Frank", "Grace", "Hannah","Sakib"],
    "City": ["New York", "Los Angeles", "Newark", "Boston", "New Delhi", "Chicago", "New Orleans", "Houston","H Los Ang"],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "Marketing", "Finance", "HR", "HR"],
    "Salary": [50000, 60000, 55000, 70000, 52000, 58000, 62000, 51000,70000]
}

df = pd.DataFrame(data)

df

      Name         City Department  Salary
0    Alice     New York         HR   50000
1      Bob  Los Angeles         IT   60000
2  Charlie       Newark    Finance   55000
3    David       Boston         IT   70000
4      Eve    New Delhi         HR   52000
5    Frank      Chicago  Marketing   58000
6    Grace  New Orleans    Finance   62000
7   Hannah      Houston         HR   51000
8    Sakib    H Los Ang         HR   70000

In [ ]:
# Filter rows where 'City' contains 'New' (case-sensitive)
df.loc[df['City'].str.contains('New')]

# Filter rows where 'City' contains 'new' (case-insensitive)
df.loc[df['City'].str.contains('new',case=False)]

# Filter rows where 'City' contains the regex pattern 'Los'
df.loc[df['City'].str.contains(r"Los")]

# Filter rows where 'City' contains the regex pattern 'Los' (case-insensitive)
df.loc[df['City'].str.contains(r"^Los")]

# Filter rows where 'City' contains the regex pattern 'rk$'
df.loc[df['City'].str.contains(r"rk$")]

# Filter rows where 'Name' starts with a vowel (A, E, I, O, U)
df.loc[df['Name'].str.contains(r"^[AEIOU]")]
df.loc[df['Name'].str.contains(r"^[AEIOU]", case=False)]

# Filter rows where 'City' contains either 'New' or 'Los'
df.loc[df['City'].str.contains(r"New|Los")]

      Name         City Department  Salary
0    Alice     New York         HR   50000
1      Bob  Los Angeles         IT   60000
2  Charlie       Newark    Finance   55000
4      Eve    New Delhi         HR   52000
6    Grace  New Orleans    Finance   62000
8    Sakib    H Los Ang         HR   70000